"use client";

import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Target, Server, Clock, CheckCircle, AlertTriangle, Layers } from 'lucide-react';

const Card = ({ title, icon: Icon, children, delay }) => (
  <motion.div 
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.5, delay }}
    className="liquid-glass p-6 rounded-3xl border border-white/5"
  >
    <div className="flex items-center gap-3 mb-4">
      <div className="p-2 rounded-full bg-white/5">
        <Icon size={18} className="text-gray-400" />
      </div>
      <h3 className="text-sm uppercase tracking-widest text-gray-400">{title}</h3>
    </div>
    <div className="text-gray-300 text-sm leading-relaxed">
      {children}
    </div>
  </motion.div>
);

const GeneratedPRD = ({ onNext, requestId }) => {

  const [request, setRequest] = useState(null);

  useEffect(() => {
    if (!requestId) return;

    const loadPRD = async () => {
      const res = await fetch(
        `https://project-hive-backend-iiud.onrender.com/business-requests/${requestId}`
      );

      const data = await res.json();
      setRequest(data);
    };

    loadPRD();
  }, [requestId]);

if (!request) {
  return (
    <div className="min-h-screen bg-black flex items-center justify-center text-white">
      Loading AI Project Blueprint...
    </div>
  );
}

  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-12 font-sans">
      <div className="max-w-6xl mx-auto">
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mb-12"
        >
          <h1 className="text-4xl md:text-5xl font-light mb-4">Project Blueprint</h1>
          <p className="text-gray-500">Requirements Engineer & Solution Architect output</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          <Card title="Problem" icon={AlertTriangle} delay={0.1}>
            {request.description}
          </Card>
          <Card title="Objectives" icon={Target} delay={0.2}>
            {request.prd?.substring(0,180)}...
          </Card>
          <Card title="Tech Stack" icon={Server} delay={0.3}>
            {request.tech_stack
  ? JSON.stringify(request.tech_stack)
  : "Generated by AI"}
          </Card>
          <Card title="Architecture" icon={Layers} delay={0.4}>
            AI Requirements Agent → Solution Architect → Talent Scout → Project Dashboard
          </Card>
          <Card title="Timeline" icon={Clock} delay={0.5}>
           Status: {request.status}
          </Card>
          <Card title="Deliverables" icon={CheckCircle} delay={0.6}>
            Business Request ✔
AI Generated PRD ✔
Student Matching ✔
Project Dashboard ✔
          </Card>
        </div>

        <div className="flex justify-center">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={onNext}
            className="bg-white text-black px-8 py-3 rounded-full font-medium hover:bg-gray-200"
          >
            Match Talent
          </motion.button>
        </div>
      </div>
    </div>
  );
};

export default GeneratedPRD;
